### ISSUE TITLE
qiita post できません

### ISSUE THREAD

**Issue by djj31370** [yamatoken/qiita_org#18]
いつも使わせて頂いてます.
qiita_org のバージョンを 0.1.32 にしたらできなくなりました.
よろしくおねがいします。
``` bash
$ qiita post README.org
Traceback (most recent call last):
	7: from /usr/local/bin/qiita:23:in `<main>'
	6: from /usr/local/bin/qiita:23:in `load'
	5: from /var/lib/gems/2.5.0/gems/qiita_org-0.1.32/exe/qiita:3:in `<top (required)>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /var/lib/gems/2.5.0/gems/qiita_org-0.1.32/lib/qiita_org.rb:13:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /var/lib/gems/2.5.0/gems/qiita_org-0.1.32/lib/qiita_org/upload.rb:101: void value expression (SyntaxError)
..., file_name))? @file_url : next
...                               ^
```

**Comment by daddygongon** [comment]
えっと，issue #17"動きません"と同じですね．最新版で動くようになったのと違いましたっけ？
今は，0.1.32が最新のようですね．あってます？
closedしていますが，今後もこのような問い合わせがくるときに，どう解決したのか，「最新版を再度インストールしなおしてください」とかがわかるように#17に解決策を書くようにしましょう．

**Comment by daddygongon** [comment]
修正版0.1.33がgithubにあります．そちらをinstallしてみてください．public releaseもすぐにされると思います．

**Comment by yamatoken** [comment]
0.1.33をreleaseしました。遅くなってしまい申し訳ありません。
