### ISSUE TITLE
tagを書き込むとエラーが出ます

### ISSUE THREAD

**Issue by daddygongon** [yamatoken/qiita_org#23]
タグの強制入力を使ったところ以下のようなエラーが出ました．
``` 
Please input tags, or 'e' for end.
"tag1:"
github
"tag2:"
e
Traceback (most recent call last):
	13: from /Users/bob/.rbenv/versions/2.7.1/bin/qiita:23:in `<main>'
	12: from /Users/bob/.rbenv/versions/2.7.1/bin/qiita:23:in `load'
	11: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/exe/qiita:5:in `<top (required)>'
	10: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	 9: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 8: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 7: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 6: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org.rb:39:in `post'
	 5: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org/get_multiple_files.rb:19:in `run'
	 4: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org/get_multiple_files.rb:19:in `each'
	 3: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org/get_multiple_files.rb:29:in `block in run'
	 2: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org/post.rb:215:in `run'
	 1: from /Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org/post.rb:32:in `get_title_tags'
/Users/bob/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/qiita_org-0.1.39/lib/qiita_org/post.rb:47:in `check_tags': undefined method `split' for ["github"]:Array (NoMethodError)
```
よろしくご対応をお願いします．

**Comment by yamatoken** [comment]
ご報告ありがとうございます．
強制入力で入力するTagが一つだけだと，処理の問題でエラーが出ていたようです．
post.rbのTagの処理方法を変更してこれを解決しました．

0.1.40を公開しましたので，確認よろしくお願いします．

**Comment by daddygongon** [comment]
ごめんなさい．「うまく動いています」の報告を忘れてました．本来は私がcloseすべきでした．申し訳ない．
